/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\686e86ca3c5db6e0e80c6464.glb
*/

import React, { useEffect, useRef, useState } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'; // Import THREE for blending modes

// Per-transition crossfade duration. Poses that are close to each other
// (e.g. Falling -> StandingUp, StandingUp -> Waving) can blend fast.
// Poses that are far apart (Standing -> horizontal Flying) need more
// time or the skeleton visibly "collapses" mid-blend.
const TRANSITION_DURATIONS = {
  FlyingPose:0.5,
  StandingUp: 0.5,
  Waving: 0.4,
  Flying: 0.5,   // standing -> prone/horizontal needs a longer blend
  Falling: 0.6,  // flying -> falling, also a big pose change
};
const DEFAULT_TRANSITION_DURATION = 0.5;

export function Avatar(props) {
  const groupRef = useRef();
  const { scene } = useGLTF('models/686e86ca3c5db6e0e80c6464.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const newAnimation = useRef();
  const group2ref = useRef();

  const { animations: fallingAnimation } = useFBX('/animations/Falling.fbx');
  const { animations: wavingAnimation } = useFBX('/animations/Waving.fbx');
  const { animations: standingUpAnimation } = useFBX('/animations/Standing Up.fbx');  
  const { animations: flyingAnimation } = useFBX('/animations/FlyingVertical2.fbx');
  const {animations: flyingPose} = useFBX('/animations/FlyingPose.fbx');

  fallingAnimation[0].name = "Falling";

  wavingAnimation[0].name = "Waving";

  standingUpAnimation[0].name = "StandingUp";
  flyingAnimation[0].name = "Flying";
  flyingPose[0].name="FlyingPose"

    // --- Strip baked root-motion from the Flying clip ---
  // Keep the Hips vertical (Y) offset — that's what holds the pose above
  // the ground — but zero out horizontal (X/Z) drift and drop scale tracks.
  let flyingBaseY = 0;
  // flyingAnimation[0].tracks = flyingAnimation[0].tracks
  //   .map((track) => {
  //     const n = track.name.toLowerCase();
  //     if (n.includes('.scale')) return null; // drop scale tracks entirely

  //     if (n.includes('.position')) {
  //       const values = track.values.slice(); // [x0,y0,z0, x1,y1,z1, ...]
  //       if (n.includes('hips')) {
  //         flyingBaseY = values[1]; // capture frame-0 height before zeroing
  //       }
  //       for (let i = 0; i < values.length; i += 3) {
  //         values[i] = 0;     // x
  //         values[i + 2] = 0; // z
  //         // leave values[i+1] (y) untouched so the float height survives
  //       }
  //       track.values = values;
  //       return track;
  //     }

  //     return track; // rotation/quaternion tracks etc. pass through untouched
  //   })
  //   .filter(Boolean);

  // Combine all animations into a single array for useAnimations
  const allAnimations = [
    fallingAnimation[0],

    wavingAnimation[0],
    standingUpAnimation[0],
    flyingAnimation[0],
    flyingPose[0]
  ];

  const { actions, mixer } = useAnimations(allAnimations, groupRef);

  const rotateRef = useRef();
  // Keep track of the currently active animation
  const currentAction = useRef(null);

  // --- Falling Y-axis movement config ---
  const FALL_START_Y = 2;   // height the avatar starts falling from
  const FALL_END_Y = 0;     // ground/rest position
  const isFallingRef = useRef(false);
  const fallStartYRef = useRef(FALL_START_Y);

   const FLY_START_Y = 0;   // height the avatar starts falling from
  const FLY_END_Y = 2;     // ground/rest position
  const isFlyingRef = useRef(false);
  const flyStartYRef = useRef(FALL_START_Y);


  useEffect(() => {
    // Initialize all actions to be ready but not actively playing
    Object.values(actions).forEach(action => {
      action.setEffectiveWeight(0); // Set weight to 0
      action.enabled = true;      // Enable them so they can be blended
      action.play();              // Start them playing in the background (weight 0 means no visual effect)
      action.clampWhenFinished = true; // For one-shot animations like 'Hello'
    });

    actions["Waving"].setLoop(THREE.LoopOnce, 0);
    actions["Falling"].setLoop(THREE.LoopOnce, 0);
    actions["StandingUp"].setLoop(THREE.LoopOnce, 0);
    actions["Flying"].setLoop(THREE.LoopOnce, 0);
    actions["FlyingPose"].setLoop(THREE.LoopOnce, 0);

    // Start with a default animation, e.g., "Falling"
    const initialAction = actions["Falling"];
    if (initialAction) {
      initialAction.timeScale = 2;
      // Position the avatar at the fall start height before playing
      if (groupRef.current) {
        groupRef.current.position.y = FALL_START_Y;
      }
      fallStartYRef.current = FALL_START_Y;
      isFallingRef.current = true;
      initialAction.reset().fadeIn(0.5).setEffectiveWeight(1).play();
      currentAction.current = initialAction;
    }

    // Chain the animation sequence: Falling -> StandingUp -> Waving ->
    // Flying -> Falling (loop).
    const onAnimationFinish = (e) => {
      const finishedName = e.action.getClip().name;
      console.log(finishedName,"====here====")
      const stillRelevant =
        currentAction.current === actions[finishedName];

      if (!stillRelevant) return;
      if (finishedName === "Falling") {
        isFallingRef.current = false;
        transitionToAnimation("StandingUp");
      }
      if (finishedName === "StandingUp") {
        transitionToAnimation("Waving");
      } 
      else if (finishedName === "Waving") {
        transitionToAnimation("FlyingPose");
      }
      else if(finishedName === "FlyingPose"){
         isFlyingRef.current = true;
        transitionToAnimation("Flying");
      }
      else if (finishedName === "Flying") {
        isFlyingRef.current = false;
        transitionToAnimation("Falling");
      }
    };

    mixer.addEventListener('finished', onAnimationFinish);

    // Clean up event listener
    return () => {
      mixer.removeEventListener('finished', onAnimationFinish);
    };

  }, [actions, mixer]); // Depend on actions and mixer so this runs once after they are available

  // Function to smoothly transition between animations
  const transitionToAnimation = (name, durationOverride) => {
    const newAction = actions[name];
    if (newAction && newAction !== currentAction.current) {
      const duration =
        durationOverride ?? TRANSITION_DURATIONS[name] ?? DEFAULT_TRANSITION_DURATION;

      const previousAction = currentAction.current;

      if (name === "StandingUp" || name === "Falling") {
        newAction.timeScale = 2;
      }
      else if(name === "FlyingPose"){
        newAction.timeScale = 5;
      }
      else {
        newAction.timeScale = 1;
      }

      // 1. Prepare and start the incoming action cleanly
      newAction
        .reset()
        .setEffectiveTimeScale(newAction.timeScale)
        .setEffectiveWeight(1)
        .fadeIn(duration)
        .play();

      // 2. Crossfade from the old action to the new one
      if (previousAction) {
        previousAction.crossFadeTo(newAction, duration, false);
      }

      currentAction.current = newAction;
      newAnimation.current = name;

      // Handle Falling-specific position setup/teardown
      if (name === "Falling") {
        isFallingRef.current = true;
        if (groupRef.current) {
          fallStartYRef.current = groupRef.current.position.y;
        }
      } else if (previousAction === actions["Falling"]) {
        isFallingRef.current = false;
        if (groupRef.current) {
          groupRef.current.position.y = FALL_END_Y;
        }
      }
      // Snap to the height baked into the Flying clip so the horizontal
      // pose doesn't clip through the floor.
      if (name === "Flying" && groupRef.current) {
        console.log("====here====",FLY_START_Y)
        groupRef.current.position.y = FLY_START_Y;
      }

    }
  };

  // Example of how you might trigger animations from props or state changes
  useEffect(() => {
    if (props.animationState) {
      transitionToAnimation(props.animationState);
    }
  }, [props.animationState]);

  useFrame((state, delta) => {
    // if (rotateRef.current && group2ref.current.rotation.z <= 2) {
    //   group2ref.current.rotation.z += 0.01;
    // }

    // Drive the Y-axis drop while the Falling animation is active
    const fallingAction = actions["Falling"];
    const flyingAction = actions["Flying"];
    if (
      isFallingRef.current &&
      fallingAction &&
      currentAction.current === fallingAction &&
      groupRef.current
    ) {
      const clipDuration = fallingAction.getClip().duration;
      const progress = THREE.MathUtils.clamp(fallingAction.time / clipDuration, 0, 1);
      groupRef.current.position.y = THREE.MathUtils.lerp(fallStartYRef.current, FALL_END_Y, progress);
    }

    if (
      isFlyingRef.current &&
      flyingAction &&
      currentAction.current === flyingAction &&
      groupRef.current
    ) {
      const clipDuration = flyingAction.getClip().duration;
      const progress = THREE.MathUtils.clamp(flyingAction.time / clipDuration, 0, 1);
      groupRef.current.position.y = THREE.MathUtils.lerp(FLY_START_Y, FLY_END_Y, progress);
    }

    // Drive the Y-axis bob while the Flying animation is active.

  })

  Object.values(materials).forEach((material) => {
    material?.emmisive?.set('#ff00ff');
  })

  return (
    <group {...props} ref={groupRef} dispose={null}>
      <group rotation-x={-Math.PI / 2} ref={group2ref}>
        <primitive object={nodes.Hips} />
        <skinnedMesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
        <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
        <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
        <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
        <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
        {(props.animationState === "TypingX" || props.animationState === "Hello") && <mesh scale={[0.8, 0.5, 0.8]} position-z={0}>
          <boxGeometry />
          <meshStandardMaterial color="white" />
        </mesh>}
      </group>
    </group>
  )
}

useGLTF.preload('models/686e86ca3c5db6e0e80c6464.glb')