/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\686e86ca3c5db6e0e80c6464.glb
*/

import React, { useEffect, useRef, useState } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'; // Import THREE for blending modes

export function Avatar(props) {
  const groupRef = useRef();
  const { scene } = useGLTF('models/686e86ca3c5db6e0e80c6464.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const newAnimation = useRef();
  const group2ref = useRef();

  const { animations: typingAnimation } = useFBX('/animations/Typing.fbx');
  const { animations: fallingAnimation } = useFBX('/animations/Falling.fbx');
  const { animations: standingAnimation } = useFBX('/animations/Standing.fbx');
  const { animations: helloAnimation } = useFBX('/animations/Asking Question.fbx');
  const { animations: sitToType } = useFBX('/animations/Sit To Type.fbx');
  const { animations: wavingAnimation } = useFBX('/animations/Waving.fbx');
  const { animations: typing2Animation } = useFBX('/animations/Typing2.fbx');
  const { animations: typingXAnimation } = useFBX('/animations/TypingX.fbx');

  typingAnimation[0].name = "Typing";
  fallingAnimation[0].name = "Falling";
  standingAnimation[0].name = "Standing";
  helloAnimation[0].name = "Hello";
  sitToType[0].name = "Sitting";
  wavingAnimation[0].name = "Waving";
  typing2Animation[0].name = "Typing2";
  typingXAnimation[0].name = "TypingX";
  // Combine all animations into a single array for useAnimations
  const allAnimations = [
    typingAnimation[0],
    fallingAnimation[0],
    standingAnimation[0],
    helloAnimation[0],
    sitToType[0],
    wavingAnimation[0],
    typing2Animation[0],
    typingXAnimation[0],
  ];

  const { actions, mixer } = useAnimations(allAnimations, groupRef);
  // const meshRef = useRef();

  const rotateRef = useRef();
  // Keep track of the currently active animation
  const currentAction = useRef(null);

  useEffect(() => {
    // Initialize all actions to be ready but not actively playing
    Object.values(actions).forEach(action => {
      action.setEffectiveWeight(0); // Set weight to 0
      action.enabled = true;      // Enable them so they can be blended
      action.play();              // Start them playing in the background (weight 0 means no visual effect)
      action.clampWhenFinished = true; // For one-shot animations like 'Hello'
    });

    actions["Hello"].setLoop(THREE.LoopOnce, 0);
    actions["Waving"].setLoop(THREE.LoopOnce, 0);
    actions["Typing2"].setLoop(THREE.LoopOnce, 0);
    actions["Standing"].setLoop(THREE.LoopOnce, 0);
    // console.log(actions["Hello"])

    // Start with a default animation, e.g., "Standing"
    const initialAction = actions["Standing"];
    if (initialAction) {
      initialAction.reset().fadeIn(0.5).setEffectiveWeight(1).play();
      currentAction.current = initialAction;
    }

    // You can also set a listener for when a one-shot animation finishes
    // For example, after "Hello" finishes, transition back to "Standing"
    const onAnimationFinish = (e) => {
      const finishedName = e.action.getClip().name;
      const stillRelevant =
        currentAction.current === actions[finishedName];

      if (!stillRelevant) return;

      if (finishedName === "Standing") {
        transitionToAnimation("Waving", 0.5);
      } else if (finishedName === "Waving") {
        transitionToAnimation("Standing", 0.5);
      }
    };

    mixer.addEventListener('finished', onAnimationFinish);

    // Clean up event listener
    return () => {
      mixer.removeEventListener('finished', onAnimationFinish);
    };

  }, [actions, mixer]); // Depend on actions and mixer so this runs once after they are available

  // Function to smoothly transition between animations
  const transitionToAnimation = (name, duration = 0.5) => {
    console.log("====here=====")
    const newAction = actions[name];
    if (newAction && newAction !== currentAction.current) {
      // Fade out the current action and fade in the new one
      currentAction.current.crossFadeTo(newAction, duration, true); // true for warpBoolean
      currentAction.current.fadeOut(0.5); // Ensure it explicitly fades out

      newAction.reset().fadeIn(0.5).setEffectiveWeight(1).play();
      currentAction.current = newAction;
      newAnimation.current = name;
      // props.setAnimationChanged(!props.setAnimationChanged);
    }
  };

  // Example of how you might trigger animations from props or state changes
  // For instance, if you have a prop `animationState`
  useEffect(() => {
    if (props.animationState) {
      transitionToAnimation(props.animationState, 0.5);
    }
  }, [props.animationState]);

  useFrame((state) => {
    if (rotateRef.current && group2ref.current.rotation.z <= 2) {
      group2ref.current.rotation.z += 0.01;
    }
    // groupRef.current.getObjectByName("Head").lookAt(state.camera.position)
    // console.log(group2ref.current.rotation.z);
  })


  // useFrame(() => {
  //   // console.log(newAnimation)
  //   // if (meshRef.current && newAnimation.current === "TypingX") {
  //   //   if(meshRef.current.position.y <0){
  //   //      meshRef.current.position.y += 0.01
  //   //   }
  //   //   else{
  //   //     newAnimation.current = false;
  //   //   }
  //     // console.log("====inside======")
  //     // Move backwards

  //   }
  // })

  // console.log(nodes)

  Object.values(materials).forEach((material) => {
    // material.wireframe = true

    // material.vertexColors = false;
    // material.visible = false;
    // material?.specularColor?.set("#ff0000")
    material?.emmisive?.set('#ff00ff');
    // material.blendColor.set("#0000ff")
    // material.color.r = 0;
    // material.color.g = 0;
    // material.color.b = 1;

    // material.blendColor.r= 0;
    // material.blendColor.g=0;
    // material.blendColor.b=1;

    // material?.emmisive?.r=0;
    // material?.emmisive?.g=0;
    // material?.emmisive?.b=1;
    // material.attenuationColor.g=0;
    // material.attenuationColor.b=1;
  })

  // const material = new THREE.MeshStandardMaterial({ color: 0x00ff00 });
  // console.log(materials)
  console.log(props.animationState)
  return (
    <group {...props} ref={groupRef} dispose={null}>
      <group rotation-x={-Math.PI / 2} ref={group2ref}>
        <primitive object={nodes.Hips} />
        <skinnedMesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
        <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
        <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
        <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
        <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
        {(props.animationState === "TypingX" || props.animationState === "Hello") && <mesh scale={[0.8, 0.5, 0.8]} position-z={0}>
          <boxGeometry />
          <meshStandardMaterial color="white" />
        </mesh>}
      </group>
    </group>
  )
}

useGLTF.preload('models/686e86ca3c5db6e0e80c6464.glb')